[package]
name = "tree-sitter-mojo"
description = "Mojo grammar for tree-sitter"
version = "0.1.0"
authors = ["Aditya Singh <1adityasingh@proton.me>"]
license = "MIT"
readme = "README.md"
keywords = ["incremental", "parsing", "tree-sitter", "mojo"]
categories = ["parser-implementations", "parsing", "text-editors"]
repository = "https://github.com/adityasz/tree-sitter-mojo"
edition = "2021"
autoexamples = false

build = "bindings/rust/build.rs"
include = [
  "bindings/rust/*",
  "grammar.js",
  "queries/*",
  "src/*",
  "tree-sitter.json",
  "LICENSE",
]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter-language = "0.1"

[build-dependencies]
cc = "1.2"

[dev-dependencies]
tree-sitter = "0.25.3"
